### ISSUE TITLE
[Troubleshoot] Depscan reporting nothing

### ISSUE THREAD

**Issue by gitnachogo** [ShiftLeftSecurity/sast-scan#197]
Hi!
I am integrating ShiftLeft Scan into my organization's GitLab CI/CD environment using this .gitlab-ci.yml for a maven project:
```
scan:
  stage: 'test'
  image: docker:stable
  script:
    - mkdir -p db
    - ls -la
    - docker run -e "VDB_HOME=/db" -e "SCAN_DEBUG_MODE=debug" -e "WORKSPACE=${CI_PROJECT_DIR}" -e "GITHUB_TOKEN=${GITHUB_TOKEN}" -v "${CI_PROJECT_DIR}/db:/db" -v "${CI_PROJECT_DIR}:/app" shiftleft/sast-scan scan --src /app --type depscan
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - reports/
    when: always
  tags:
    - docker-build
```
I create the /db directory, mounting it to /db and setting the VDB_HOME to /db, just in case this was the error, because before doing it, it tried to do `mkdir` on /.local and it had no permissions to do so. The output of the tool is the following one:
![image](https://user-images.githubusercontent.com/67385224/92729862-3db0b180-f373-11ea-9bf2-212659b4b129.png)
I do not know why it shows the SAST scan summary if only the depscan was created; and in addition, nothing is generated to reports.
Thanks in advance.
PS: before this script, there is no reports folder. And yess, I've setted the GITHUB_TOKEN as `read:packages` in the project's variables

**Comment by prabhu** [comment]
Hi,

Can you try passing the source directory like this - `--src ${CI_PROJECT_DIR}`

```
variables:
  GITHUB_TOKEN: $GITHUB_TOKEN
scan:
  stage: test
  image:
    name: shiftleft/sast-scan
  script:
    - scan --build --src ${CI_PROJECT_DIR} --type depscan --out_dir ${CI_PROJECT_DIR}/reports
  rules:
    - when: always
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/reports/
    when: always
```

Regarding SAST scan is there an existing reports directory in the repo containing some sarif files? It seems to be picking some files from somewhere.
`
