### ISSUE TITLE
Do not drop the build if issue is found

### ISSUE THREAD

**Issue by nickbabkin** [ShiftLeftSecurity/sast-scan#275]
Hi @prabhu. Thanks for this swiss-army knife of a project.
We're currently piloting it on CircleCI and I'm using this simple config to trigger the scan:

```
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Comment
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: shiftleft/sast-scan
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Perform ShiftLeft Scan
          command: |
            scan -t go
      - store_artifacts:
          path: reports
          destination: sast-scan-reports
```

It seems to work fine except one thing. During the pilot phase, I would like to not drop the build but rather just inform about issues found. What configuration options shall I use to trigger this behavior? Also, is there a flexibility (like drop the build if critical or high severity issue is found, but don't drop when it's only medium-low-informational?)

Thanks!
