### ISSUE TITLE
Not able to see scan result in dev azure due to sarif file empty

### ISSUE THREAD

**Issue by anime-shed** [ShiftLeftSecurity/sast-scan#400]
HTML contains scan result but sarif file is empty
![image](https://github.com/ShiftLeftSecurity/sast-scan/assets/67512697/459f833d-5e71-4f6f-b8c6-881ba659edce)

![image](https://github.com/ShiftLeftSecurity/sast-scan/assets/67512697/db463e05-45e9-4990-8e83-2a4f12214b45)

Yml for pipeline:
```
trigger:
  branches:
    include:
      - master
pool:
 vmImage: ubuntu-latest

container: shiftleft/sast-scan:latest

steps:
    - script: scan --build --type depscan --out_dir $(Build.ArtifactStagingDirectory)/CodeAnalysisLogs
      displayName: "Perform Vulnerability Scan"
      continueOnError: "true"

    - task: PublishBuildArtifacts@1
      displayName: "Publish scan logs"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs'
        ArtifactName: 'CodeAnalysisLogs'
        publishLocation: 'Container'
        StoreAsTar: true
```
